### ISSUE TITLE
程序似乎无法区分签到活动和作业活动

### ISSUE THREAD

**Issue by billionray** [LnYo-Cly/ChaoXingAutoSign#1]
马克思主义基本原理------检测到：4个活动。 Traceback (most recent call last):   File "./AutoSign.py", line 138, in <module>     qiandao(course_dict[currClass][1],address,sleepTime,SENDKEY)   File "./AutoSign.py", line 91, in qiandao     enc=session.get('https://mobilelearn.chaoxing.com/v2/apis/sign/refreshQRCode?activeId={id}'.format(id=id[0])).json()['data']['enc'] TypeError: 'NoneType' object is not subscriptable Error: Process completed with exit code 1.
其中这四个活动是作业活动，而程序将其视为签到活动并尝试签到，签到失败后报错

**Comment by LnYo-Cly** [comment]
已经更新，试试新版

**Comment by billionray** [comment]
成功了，感谢
